[package]
name = "function_inlining_1"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "lab"
harness = false

[dependencies]
libc = "0.2.131"
rand = "0.8.5"

[dev-dependencies]
criterion = "0.3.6"
