[package]
name = "warmup"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "lab"
harness = false

[profile.release]
debug = true
