[package]
name = "warmup"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "bench_warmup"
harness = false

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports", "real_blackbox", "cargo_bench_support"] }
